name: CI
on:
  push: { branches: [main, master] }
  pull_request: { branches: ["**"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper monorepo analysis

      - uses: pnpm/action-setup@v4  # Should come BEFORE node setup
        with:
          version: 10.14.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify versions
        run: |
          node --version
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test

      - name: Build packages
        run: pnpm run build